const sampleData = {
  products: [
    {
      name: 'Modern Stainless Steel Watering Can',
      slug: 'modern-stainless-steel-watering-can',
      category: 'Watering Gear',
      description: 'Sleek silver watering can with a long spout for precise watering of indoor plants.',
      images: [
        '/images/sample-products/p1-1.png',
        '/images/sample-products/p1-2.png',
        '/images/sample-products/p1-3.png',
      ],
      price: 34.99,
      brand: 'Urban Green',
      rating: 4.8,
      numReviews: 24,
      stock: 15,
      isFeatured: true,
      banner: '/images/sample-products/banner-1.png',
    },
    {
      name: 'Bamboo Plant Support Kit',
      slug: 'bamboo-plant-support-kit',
      category: 'Plant Accessories',
      description: 'Natural bamboo stakes with twine and clips to support climbing plants like Pothos and Ivy.',
      images: [
        '/images/sample-products/p2-1.png',
        '/images/sample-products/p2-2.png',
      ],
      price: 19.99,
      brand: 'NatureGrow',
      rating: 4.3,
      numReviews: 10,
      stock: 40,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Plant Shield Natural Pest Control',
      slug: 'plant-shield-natural-pest-control',
      category: 'Plant Care',
      description: 'Organic spray to protect your indoor garden from common pests without harsh chemicals.',
      images: [
        '/images/sample-products/p3-1.png',
        '/images/sample-products/p3-2.png',
        '/images/sample-products/p3-3.png',
      ],
      price: 24.50,
      brand: 'Plant Shield',
      rating: 4.9,
      numReviews: 45,
      stock: 20,
      isFeatured: true,
      banner: '/images/sample-products/banner-3.png',
    },
    {
      name: 'Digital Soil Moisture Meter',
      slug: 'digital-soil-moisture-meter',
      category: 'Tools',
      description: 'Precision digital meter to instantly check soil moisture levels and prevent over-watering.',
      images: [
        '/images/sample-products/p4-1.png',
        '/images/sample-products/p4-2.png',
      ],
      price: 29.95,
      brand: 'TechGarden',
      rating: 4.6,
      numReviews: 32,
      stock: 12,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Minimalist Ceramic Pot Set',
      slug: 'minimalist-ceramic-pot-set',
      category: 'Pots & Planters',
      description: 'A trio of earth-toned ceramic and terracotta pots to complement any interior decor.',
      images: [
        '/images/sample-products/p5-1.png',
        '/images/sample-products/p5-2.png',
        '/images/sample-products/p5-3.png',
      ],
      price: 55.00,
      brand: 'Clay & Co',
      rating: 4.7,
      numReviews: 18,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'Plant Nourish Organic Fertilizer',
      slug: 'plant-nourish-organic-fertilizer',
      category: 'Plant Care',
      description: 'Concentrated organic liquid plant food in a vintage-style amber glass bottle.',
      images: [
        '/images/sample-products/p6-1.png',
        '/images/sample-products/p6-2.png',
      ],
      price: 18.99,
      brand: 'Plant Nourish',
      rating: 5.0,
      numReviews: 60,
      stock: 25,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'Vintage Glass Plant Mister',
      slug: 'vintage-glass-plant-mister',
      category: 'Watering Gear',
      description: 'Elegant smoked glass spray bottle with brass mechanism for humidity-loving tropicals.',
      images: [
        '/images/sample-products/p7-1.png',
        '/images/sample-products/p7-2.png',
      ],
      price: 22.50,
      brand: 'Botanica',
      rating: 4.4,
      numReviews: 15,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Premium Organic Potting Mix',
      slug: 'premium-organic-potting-mix',
      category: 'Soil & Substrates',
      description: 'Nutrient-rich potting soil blend in a burlap sack, perfect for repotting indoor plants.',
      images: [
        '/images/sample-products/p8-1.png',
      ],
      price: 15.99,
      brand: 'Earth First',
      rating: 4.8,
      numReviews: 85,
      stock: 50,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Indoor Gardening Tool Trio',
      slug: 'indoor-gardening-tool-trio',
      category: 'Tools',
      description: 'Essential set containing a trowel, rake, and pruning shears with wooden handles.',
      images: [
        '/images/sample-products/p9-1.png',
      ],
      price: 39.99,
      brand: 'HandyGarden',
      rating: 4.5,
      numReviews: 22,
      stock: 14,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Full Spectrum LED Grow Light',
      slug: 'full-spectrum-led-grow-light',
      category: 'Lighting',
      description: 'Adjustable LED grow light with multiple heads to ensure healthy growth in low-light areas.',
      images: [
        '/images/sample-products/p10-1.png',
      ],
      price: 65.00,
      brand: 'Plant Glow',
      rating: 4.9,
      numReviews: 55,
      stock: 6,
      isFeatured: true,
      banner: '/images/sample-products/banner-10.png',
    },
  ],
};

export default sampleData;